spring:
  application:
    name: app-desafio

  datasource:
    url: jdbc:postgresql://localhost:5432/produtos
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update